name: SonarCloud Analysis
on: 
  push:
    branches: [ main, master ]
  pull_request: 
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarCloud analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          if [ -d "tests" ] || ls test_*.py 1> /dev/null 2>&1; then
            pytest --cov=./ --cov-report=xml
          else
            echo "No tests found - creating empty coverage.xml"
            echo '<coverage></coverage>' > coverage.xml
          fi

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=AashikaShravani_Credit_Risk_Analysis
            -Dsonar.organization=AashikaShravani
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
